#! /bin/bash
# 
# This script informs supervisor to start a given project that is specified in
# the config.sh file.
# 

main() {
  USER=$(whoami)
  source /home/${USER}/deployment/.env
  supervisorctl start ${PROJECT}
}

main
