#! /bin/bash
# 
# This script informs supervisor to start a given GITHUB_REPO that is specified in
# the config.sh file.
# 

main() {
  USER=$(whoami)
  source /home/${USER}/deployment/.env
  supervisorctl start ${GITHUB_REPO}
}

main
