#! /bin/bash
# 
# This script informs supervisor to stop a given project that is specified in
# the config.sh file.
# 

main() {
  source /home/${USER}/deployment/.env
  supervisorctl stop ${PROJECT}
}

main
