#! /bin/bash
# 
# This script pulls the latest version of the github repository for a project. 
# Supervisor is used to stop the current gunicorn command that runs the
# website. Any updates to the flask application are made and then supervisor
# starts a new server.
# 

main(){
  source /home/${USER}/deployment/.env
  cd /home/${USER}/${PROJECT}
  source venv/bin/activate
  git pull
  /home/${USER}/deployment/stop
  # flask db upgrade
  /home/${USER}/deployment/start
}

main
