#! /bin/bash
# 
# This script pulls the latest version of the github repository, GITHUB_REPO. 
# Supervisor is used to stop the current gunicorn command that runs the
# website. Any updates to the flask application are made and then supervisor
# starts a new server.
# 

main() {
  source .env
  cd /home/${SERVER_USERNAME}/${GITHUB_REPO}
  source venv/bin/activate
  git pull > /dev/null
  supervisorctl reload ${GITHUB_REPO} > /dev/null
  return 0
}

main
